### ISSUE TITLE
Talk Proposal: Predictive Autoscaling using Keda and Facebook Prophet

### ISSUE THREAD

**Issue by YourTechBud** [cloudnativevan/meetup#2]
## Talk Information

- **Draft Title:** Predictive Autoscaling using Keda and Facebook Prophet
- **Length:**
  - [ ] Lighting talk/Demo (10 min)
  - [x] Full Presentation (20 min)
- **Links:** (slides, article, notes)

- **Which dates, particularly Tue/Wed/Thu during the 3rd/4th week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) https://lu.ma/h4azy6v8?tk=cVEhDH
- **Short Summary of your talk:** Autoscaling pods in Kubernetes is slow. HPA wasn't really built to react to sudden spikes in load. These bursts of traffic results in a drop in application performance and subsequently a drop in end user experience. We don't want that. What if we could proactively scale our pods in anticipation of load? Let's find out!

**Note:** This talk may be a bit advanced for those who are new to K8s. I also have a talk on "Event driven autoscaling using Keda" which talks about ditching CPU and Memory based autoscaling in favor of L7 metrics like active http requests and queue size.

## Speaker Bio

- **Name:** Noorain Panjwani
- **Mini-bio:** (This is the introduction our emcee will give about you, one paragraph is usually best) Noorain, a.k.a. YourTechBud, is a techie turned product manager with an unending passion for Kubernetes. In the past 3 years, he has built the Kubernetes practice at Xebia to make Kubernetes accessible to all.
- **Picture for slides:** (We use this pictures to create promotional content and to present your talk in our socials.)
- **Would you like help with your presentation?** (Feedback on notes, content?) Sure.
- **Social media link(s):** (twitter, website, linkedin, etc.) https://www.linkedin.com/in/noorain-panjwani/
- **Do you agree to the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)?**
  - [x] I agree

**Comment by ShankyJS** [comment]
I personally would enjoy having this talk in our next event, lots of Kubernetes user are wasting time trying to scale everything with the HPA (Cpu/Memory) based scaling. 

+1 from me!

**Comment by ShankyJS** [comment]
Hey @YourTechBud, your talk has been approved!

For the day of the event please come 15-30 minutes before the starting time of the event so we can test the audio/video setup!

Also, you can take up to 30 minutes for your presentation including Q & A!

Thanks a lot for bringing this content to the community!

**Comment by ShankyJS** [comment]
@YourTechBud do you mind updating this issue content with your slides link?

Thanks!
