### ISSUE TITLE
Talk Proposal: How to run (streaming) databases in Kubernetes

### ISSUE THREAD

**Issue by jovezhong** [cloudnativevan/meetup#6]
## Talk Information

- **Draft Title:** How to run (streaming) databases in Kubernetes
- **Length:**
  - [ ] Lighting talk/Demo (10 min)
  - [x] Full Presentation (20 min)
- **Links:** (slides, article, notes) https://www.timeplus.com/post/streaming-database

- **Which dates, particularly Tue/Wed/Thu during the 3rd/4th week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.).    Oct 18, Friday
- **Short Summary of your talk:**
You probably know what is a database, even what is a OLAP database. Snowflake and duckdb are OLAP, while Postgresql/MySQL/Oracle are OLTP. There are some realtime OLAP databases such as Apache Pinot, ClickHouse. They can support high QPS(Query-per-second) and scan lots of data in few seconds. However they are not stream processing. Tools like Apache Flink are stream processor, but require a OLAP as the downstream, or RocksDB as the state store. These days, there is a new category called Streaming Databases, to combine OLAP with stream processing. Timeplus is one of the vendor, with open source core engine on GitHub https://github.com/timeplus-io/proton.

In this talk, I am going to share how we can easily deploy Timeplus in Kubernetes with Helm chart, while in our fully managed cloud, why we use a slightly different approach to use Kubernetes Operator to manage multi-tenants. Key technologies we are using: AWS EKS, Fargate serverless compute, Karpenter.sh, customer terraform and GitOps.

## Speaker Bio

- **Name:** Jove Zhong
- **Mini-bio:** (This is the introduction our emcee will give about you, one paragraph is usually best) Co-founder at Timeplus. Ex-Splunk, ex-EMC, ex-IBM. He is a board sports fanatic, incl. agile board.
- **Picture for slides:** (We use this pictures to create promotional content and to present your talk in our socials.)
- **Would you like help with your presentation?** (Feedback on notes, content?) Sure
- **Social media link(s):** (twitter, website, linkedin, etc.) https://www.linkedin.com/in/jovezhong/
- **Do you agree to the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)?**
  - [x] I agree

**Comment by ShankyJS** [comment]
Thanks for submitting! We will be reviewing this application soon

**Comment by ShankyJS** [comment]
Hi @jovezhong,

We discussed your content with our team and have some questions about how this topic aligns with CNCF's goal of making cloud technology ubiquitous. We aim to ensure all our topics are connected to our mission and vision for the cloud.

Do you have any other topics that might align better with cloud initiatives?

Additionally, we do have spots open for sponsored talks if you're interested in that option.

Thanks!

**Comment by jovezhong** [comment]
Thanks for the review and feedback. Will that help if I also talk about how we run our fully-managed cloud in the session? Our software can be deployed locally with few files, but also can be deployed on Kubernetes with helm chart or docker compose. In our fully-managed cloud, we use EKS and built our own Kubernetes operator to manage multi-tenant. AWS Fargate and Karpenter are used, with GitOps deployment model. 

Me or our cloud engineering lead can present this. For the audience, they will learn something know about database trends, as well as real-life lesson&learns regarding building&operating a SaaS with modern tools.

**Comment by ShankyJS** [comment]
Hey @jovezhong, what would you think about scoping this a bit differently,

The talk could be something like `Streaming databases from a Kubernetes cluster` or something like that, 

And we would love if in the content you could go through what a stateful is, if it makes sense to have db's in Kubernetes, your open source operator and all of that!

Essentially, if we make Kubernetes the main actor of this presentation this will be fully aligned!

Thanks a lot for considering giving a talk in CNCF Vancouver!

**Comment by jovezhong** [comment]
Thanks for the feedback. I have updated the original ticket with new title and summary. Look forwards to the upcoming session.

**Comment by ShankyJS** [comment]
Thanks for doing the correction @jovezhong! 

Your talk is now approved; see you in the event! Please aim to come a bit earlier (5-10 minutes) before the scheduled time to make sure we test our A/V setup! 

Thanks a lot!

**Comment by jovezhong** [comment]
Thank you, @ShankyJS  I will come early for sure. See you next Friday.

**Comment by ShankyJS** [comment]
Thank you @jovezhong please let us know if you would like us to review your slides, feel free to share with cloudnativevan@gmail.com 

Have a great night!

**Comment by jovezhong** [comment]
I just started working on the slides deck. I will also invite my colleague @ye11ow as co-presenter to share more our k8s details. Aim to share you the draft slides later this week or next Monday.

**Comment by jovezhong** [comment]
Greetings, before the long weekend, we just finished the initial draft of the talk and share you the link via email. Feel free to comment. Enjoy the long weekend and we can make updates next Tuesday.

**Comment by ShankyJS** [comment]
Thanks for the talk @jovezhong we enjoyed your presence! If in the future you would like to give another talk more focused in your product/sponsored the CNCF would love to have you!
