### ISSUE TITLE
Talk Proposal: Mastering Kubernetes Configuration Management with Kustomize

### ISSUE THREAD

**Issue by galonge** [cloudnativevan/meetup#7]
## Talk Information

- **Draft Title:*Mastering Kubernetes Configuration Management with Kustomize*
- **Length:**
  - [ ] Lighting talk/Demo (10 min)
  - [x] Full Presentation (20 min)
- **Links:** (slides, article, notes): https://www.udemy.com/course/kustomize-mastery-manage-kubernetes-configuration-with-ease

- **Which dates, particularly Tue/Wed/Thu during the 3rd/4th week of a month, are you likely available?** (e.g. "Most Thursdays with 4 weeks notice", "June or later", etc.) Available most Fridays, including Friday, Oct. 18, 2024.
- **Short Summary of your talk:**
Managing Kubernetes configurations can quickly become complex as applications grow and evolve across multiple environments. In this talk, I will demonstrate how to streamline configuration management for large-scale, multi-environment Kubernetes applications using Kustomize. Attendees will walk away with three practical strategies to simplify and scale configuration changes effectively, regardless of the application size or stage of deployment.

## Speaker Bio

- **Name:** George Alonge
- **Mini-bio:** (This is the introduction our emcee will give about you, one paragraph is usually best) DevOps Advocate and SRE with over a decade of experience architecting and scaling complex applications and infrastructure for enterprises and fast-growing startups.

- **Picture for slides:** (We use this pictures to create promotional content and to present your talk in our socials.)
- **Would you like help with your presentation?** (Feedback on notes, content?) Sure.
- **Social media link(s):** (twitter, website, linkedin, etc.) LinkedIn: https://linkedin.com/in/george-alonge,  Website: https://alonge.dev
- **Do you agree to the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)?**
  - [x] I agree

**Comment by ShankyJS** [comment]
Hey George! Thanks for submitting, we are in the process of reviewing this!

**Comment by ShankyJS** [comment]
Hey @galonge this talk has been approved, looking forward to meeting you October 18th. 

Please try to arrive to the venue at least ~15 minutes before the starting time to make sure that we test connectivity with our projector, etc.

Thanks for submitting, and we are here in case you would like us to review your slides!

**Comment by ShankyJS** [comment]
Hey @galonge is almost time for your presentation! 10 more days!

Just wanted to let you know that if you would like to get your slides reviewed by our team before the event for any typos, suggestions we are available to do so, 

Just share it with us on cloudnativevan@gmail.com

Thanks!

**Comment by ShankyJS** [comment]
Thanks again @galonge closing this issue as completed

**Comment by galonge** [comment]
Thanks for having me @ShankyJS 🙌
Looking forward to connecting again soon!
